export const educationDropdownOptions: string[] = [
    "{degree} completed at {institution} from {startDate} to {endDate}.",
    "{degree} at {institution} ({startDate} - {endDate}).",
    "{institution}: {degree} ({startDate} - {endDate}).",
    "{degree}, {institution}, ({startDate} - {endDate}).",
    "Earned a {degree} from {institution} between {startDate} and {endDate}.",
    "Studied {degree} at {institution} during {startDate} to {endDate}.",
    "Achieved {degree} ({startDate} - {endDate}) at {institution}.",
    "- {degree}, {institution} ({startDate} - {endDate})",
    "{degree}, completed at {institution} ({startDate} - {endDate})",
    "Degree: {degree} | Institution: {institution} | Duration: {startDate} - {endDate}",
    "{institution}, {degree} | ({startDate} - {endDate})",
    "Education: {degree}, {institution} ({startDate} - {endDate})",
    "{degree} | {institution} | {startDate} - {endDate}",
    "Proud graduate of {institution} with a {degree} ({startDate} - {endDate}).",
    "{degree} from {institution}, shaping my journey from {startDate} to {endDate}.",
    "{degree} ({startDate} to {endDate}) | Alma Mater: {institution}",
    "{degree} acquired at {institution} between {startDate} and {endDate}.",
    "{degree} ({startDate} - {endDate}) from the prestigious {institution}.",
    "Completed {degree} at {institution} during {startDate} to {endDate}.",
    "{institution}: {startDate} to {endDate} ({degree}).",
    "({startDate} - {endDate}): {institution}, {degree}.",
    "{startDate} - {endDate} | {degree} | {institution}.",
  ];

  export const employmentDropdownOptions: string[] = [
    "{title} at {company} from {startDate} to {endDate}.",
    "{title} ({startDate} - {endDate}) at {company}.",
    "{company}: Worked as {title} ({startDate} - {endDate}).",
    "{title}, {company}, ({startDate} - {endDate}).",
    "Served as {title} at {company} between {startDate} and {endDate}.",
    "Held the position of {title} at {company} during {startDate} to {endDate}.",
    "{title} | {company} | Duration: {startDate} - {endDate}.",
    "{company}: {title} | ({startDate} - {endDate})",
    "Position: {title} | Company: {company} | Duration: {startDate} - {endDate}.",
    "Employed as {title} at {company} from {startDate} to {endDate}.",
    "Worked as {title} at {company} ({startDate} - {endDate}).",
    "Role: {title} at {company} during {startDate} to {endDate}.",
    "Professional Experience: {title}, {company} ({startDate} - {endDate}).",
    "Proudly held the role of {title} at {company} ({startDate} - {endDate}).",
    "{title} ({startDate} to {endDate}) | Employer: {company}.",
    "{title} at {company} between {startDate} and {endDate}.",
    "{company} ({startDate} - {endDate}): {title}.",
    "Worked as {title} ({startDate} - {endDate}) at {company}.",
    "Held the title of {title} at {company} during {startDate} to {endDate}.",
    "Position: {title}, Company: {company}, Timeframe: {startDate} - {endDate}.",
    "{title} from {startDate} to {endDate} at {company}.",
    "{startDate} - {endDate} | {title} | {company}.",
    "Employment: {title}, {company} ({startDate} - {endDate}).",
    "{company}: {title} ({startDate} - {endDate}).",
  ];